# Generated by Django 4.2 on 2023-04-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=150)),
                ('cash_model', models.CharField(max_length=50)),
                ('cash_number', models.CharField(max_length=50)),
                ('register_date', models.DateField()),
                ('old_os', models.CharField(blank=True, max_length=50, null=True)),
                ('new_os', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=True)),
                ('info', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ταμειακές',
                'verbose_name_plural': 'Ταμειακές',
                'ordering': ['customer'],
            },
        ),
    ]
