# Generated by Django 4.2 on 2023-07-18 19:22

import datetime
from django.db import migrations, models
import encrypted_model_fields.fields
import tameiaki.models
import tameiaki.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=150)),
                ('cash_model', models.CharField(max_length=50)),
                ('cash_number', models.CharField(max_length=50)),
                ('register_date', models.DateField(blank=True, null=True)),
                ('old_os', models.CharField(blank=True, max_length=50, null=True)),
                ('new_os', models.CharField(blank=True, max_length=50, null=True)),
                ('update_date', models.DateField(blank=True, null=True)),
                ('aes_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, default='static/AcsServices.png', null=True, upload_to=tameiaki.models.client_directory_path, validators=[tameiaki.validators.validate_file_extension])),
            ],
            options={
                'verbose_name': 'Ταμειακές',
                'verbose_name_plural': 'Ταμειακές',
                'ordering': ['customer'],
            },
        ),
    ]
