# Generated by Django 4.2 on 2023-04-10 09:19

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('company_type', models.CharField(blank=True, max_length=150, null=True)),
                ('company_address', models.CharField(max_length=150)),
                ('company_afm', encrypted_model_fields.fields.EncryptedCharField()),
                ('phone_number', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Πελάτης',
                'verbose_name_plural': 'Πελάτης',
                'ordering': ['last_name'],
            },
        ),
    ]
