# Generated by Django 4.2 on 2023-07-18 19:33

from django.db import migrations, models
import tameiaki.models
import tameiaki.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tameiaki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=tameiaki.models.client_directory_path, validators=[tameiaki.validators.validate_file_extension]),
        ),
    ]
