# Generated by Django 4.2 on 2023-09-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tameiaki', '0002_alter_cash_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='file_url',
            field=models.URLField(default='default.jpg'),
        ),
    ]
