# Generated by Django 4.2 on 2023-04-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tameiaki', '0002_alter_cash_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
