# Generated by Django 4.2 on 2023-09-14 22:22

import datetime
from django.db import migrations, models
import tameiaki.models


class Migration(migrations.Migration):

    dependencies = [
        ('tameiaki', '0004_remove_cash_file_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.CharField(default='None', max_length=150)),
                ('archive', models.FileField(upload_to=tameiaki.models.cash_directory_path)),
            ],
            options={
                'verbose_name': 'Αρχεία',
                'verbose_name_plural': 'Αρχεία',
            },
        ),
    ]
