# Generated by Django 4.2 on 2023-09-14 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tameiaki', '0005_upload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upload',
            new_name='UploadFile',
        ),
        migrations.AlterModelTable(
            name='uploadfile',
            table='Archive',
        ),
    ]
