# Generated by Django 4.2 on 2023-06-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tameiaki', '0005_cash_aes_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
