# Generated by Django 4.2 on 2023-09-14 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tameiaki', '0006_rename_upload_uploadfile_alter_uploadfile_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='archive',
            new_name='file',
        ),
    ]
