# Generated by Django 4.2 on 2023-07-07 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tameiaki', '0006_cash_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='cash',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
