# Generated by Django 4.2 on 2023-07-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tameiaki', '0007_cash_created_at_cash_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='document',
            field=models.FileField(default='static/AcsServices.png', upload_to='documents/'),
        ),
    ]
