# Generated by Django 4.2 on 2023-09-15 22:42

from django.db import migrations, models
import tameiaki.models
import tameiaki.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tameiaki', '0007_rename_archive_uploadfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash',
            name='file',
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to=tameiaki.models.cash_directory_path, validators=[tameiaki.validators.validate_file_extension]),
        ),
    ]
