# Generated by Django 4.2 on 2023-09-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tameiaki', '0009_alter_uploadfile_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='customer',
            field=models.CharField(max_length=150),
        ),
    ]
