# Generated by Django 4.2 on 2023-07-09 07:19

from django.db import migrations, models
import tameiaki.models
import tameiaki.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tameiaki', '0009_alter_cash_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='document',
            field=models.FileField(default=None, upload_to=tameiaki.models.client_directory_path, validators=[tameiaki.validators.validate_file_extension]),
        ),
    ]
