# Generated by Django 4.2 on 2023-09-20 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tameiaki', '0010_alter_uploadfile_customer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uploadfile',
            table='CashFiles',
        ),
    ]
