# Generated by Django 4.2 on 2023-09-29 19:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tameiaki', '0011_alter_uploadfile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='cash',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='tameiaki.cash'),
        ),
    ]
