# Generated by Django 4.2 on 2023-07-10 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tameiaki', '0011_alter_cash_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cash',
            old_name='document',
            new_name='file',
        ),
    ]
