# Generated by Django 4.2 on 2023-07-10 19:49

from django.db import migrations, models
import django.db.models.deletion
import tameiaki.models
import tameiaki.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tameiaki', '0012_rename_document_cash_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='file',
            field=models.FileField(default='static/AcsServices.png', upload_to=tameiaki.models.client_directory_path, validators=[tameiaki.validators.validate_file_extension]),
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tameiaki.models.client_directory_path)),
                ('my_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tameiaki.cash')),
            ],
        ),
    ]
