# Generated by Django 4.2 on 2023-09-29 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tameiaki', '0012_uploadfile_cash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='cash',
        ),
    ]
