# Generated by Django 4.2 on 2023-09-29 22:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tameiaki', '0013_remove_uploadfile_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
