# Generated by Django 4.2 on 2023-07-10 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tameiaki', '0013_alter_cash_file_filemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileModel',
        ),
    ]
