# Generated by Django 4.2 on 2023-09-29 22:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tameiaki', '0014_uploadfile_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='id',
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
