# Generated by Django 4.2 on 2023-09-29 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tameiaki', '0015_remove_uploadfile_id_alter_uploadfile_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='uuid',
            new_name='id',
        ),
    ]
