version: '3.7'

services:
  web:
    build: .
    container_name: cash_web
    ports:
      - "5555:5555"
    volumes:
      - .:/web
      - .:/acs_cash
      - static_data:/vol/acs_cash/static/
      - static_media:/vol/acs_cash/media/
    command: gunicorn config.wsgi:application --bind 0.0.0.0:5555
    env_file:
      - .env
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
      - DATABASE_HOST=${DATABASE_HOST}
    depends_on:
      - db
  proxy:
    container_name: acs_cash_proxy
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/acs_cash/static/
      - static_media:/vol/acs_cash/media/
    ports:
      - "6560:6560"
    depends_on:
      - web 
  db:
    container_name: cash_database
    image: postgres
    volumes:
      - postgres_cash_data:/var/lib/postgressql/data
    env_file:
      - .env
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTRES_HOST}
    ports:
      - "5432:5432"
  pg_admin:
    container_name: cash_pgadmin4
    image: dpage/pgadmin4:latest
    restart: always
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LOGIN_PORT}
    ports:
      - "5550:5550"

volumes:
  postgres_cash_data:
  static_data:
  static_media: